oraidex/oraiswap-frontend

src/libs/cosmjs.ts, src/pages/Balance/index.tsx, src/pages/Swap/index.tsx, src/pages/Transfer/index.tsx
**Issue:** Keplr has updated something that broke the suggestToken feature for the old version of CosmWasm. Apparently, Keplr has completely stopped supporting the old CosmWasm.
**Reproduce:** Remove Keplr, install it again. Then enter https://oraidex.io, choose ```Swap``` tab, and it will open a new suggestion to add the CW20 token. The bug is shown below:
**How to fix:** Temporary, we need to comment out the suggestToken feature. Next, we'll read the Keplr updated code to see if there's anything that can be done. If not, then we will re-add the feature once we have upgraded the network.
=> Comment suggest token

src/__tests__/bridge.ts, src/config/bridgeTokens.ts, src/pages/Pools/LiquidityModal/LiquidityModal.tsx
- Fix SubAmount Add Liquidity
- Add testcase bridge
=> fix subamount and add testcase

src/layouts/Menu.tsx, src/libs/utils.ts, src/pages/SwapV2/Modals/SelectTokenModal.tsx
update: remove balances of Oraichain and EVM network in sidebar
=> update: remove balances of Oraichain and EVM network in sidebar

src/hooks/useTronLink.ts
fix: fix error read properties of undefined in Tronlink message
=> fix: fix error read properties of undefined in Tronlink message

src/hooks/useMetamask.ts, src/pages/Pools/indexV2.tsx
=> fix my pools

src/config/chainInfos.ts, src/libs/keplr.ts
fix: check to update Kawaiiverse info to Keplr
=> fix: check to update Kawaiiverse info to Keplr

.github/workflows/reuseable-sonar.yml, .github/workflows/reuseable-test.yml, package.json
What is the purpose of these changes?
- Update CI/CD.
Brief changelog:
- Add two workflows: run `sonarqube` and `unit-test`, trigger it when PR is created and other workflow calls
- Update engine node required for the project.
Documentation and Release note:
- Does this PR introduces new features or user-facing behaviour changes? No
- How is the feature or changes documented? No
=> add reuse workflow

src/pages/UniversalSwap/Swap/index.tsx
What is the purpose of these changes?
- Commented tax rate in universal-swap, update correct tax rate after estimate bridge fee in contract later.
=> Commented tax rate in universal-swap

src/pages/BalanceNew/KwtModal/index.tsx, src/pages/BalanceNew/index.tsx
What is the purpose of the changes?
- remove popup orderbook in home page
Brief changelog:
-  remove popup orderbook in home page 
Documentation and Release note:
- Does this change PR introduces new features or user-facing behaviour changes? Yes
- How is the feature or changes documented? No
=> update: remove popup orderbook in home page

config-overrides.js, jest.setup.ts, package.json, patches/@cosmjs+tendermint-rpc+0.31.0.patch, src/components/TVChartContainer/config.ts, src/index.tsx, src/libs/utils.ts, src/pages/Balance/index.tsx, src/pages/SwapV2/Modals/SelectTokenModal.tsx, src/polyfill.ts, src/tests/bridge-contract.spec.ts, src/types/global.d.ts, yarn.lock
- Fix error not display OHLCV in pair MILKY/USDT
- Fix error display zero OHLC in pair have price too small
=> Fix display Trading view

src/components/TVChartContainer/config.ts
What is purpose of the change?
-  force overlay volume for trading view
=> force overlay volume for trading view

src/pages/Pools/index.tsx
What is purpose of the changes? 
-  filter pool by token name
=> fix: filter pool by token name

src/config/constants.ts, src/pages/UniversalSwap/Swap/hooks/useRelayerFee.ts, src/pages/UniversalSwap/Swap/index.tsx, src/rest/api.ts
- Add relayer fee universalswap
=> add relayer fee universalswap

src/layouts/MenuV3.tsx
=> add(menu): add bridge tab

src/layouts/MenuV3.module.scss
- Fixed error display side menu in mobile
=> fix: fixed display side menu in mobile

src/layouts/MenuV3.module.scss, src/layouts/MenuV3.tsx, src/pages/Pools/components/ItemPoolMobile/ItemPoolMobile.tsx, src/pages/Pools/components/ListPool/ListPool.tsx, src/pages/UniversalSwap/Modals/SlippageModal.module.scss, src/pages/UniversalSwap/Modals/SlippageModal.tsx, src/routes.tsx
What is purpose of  the changes? 
- Styled active menu for nested route.
- Hide manual slippage to prevent crash, will update after fixed universalswap sdk
=> fix: style active menu

src/pages/Pools/components/UnstakeLPModal/UnstakeLPModal.module.scss, src/pages/Pools/components/WithdrawLiquidityModal/WithdrawLiquidityModal.module.scss, src/pages/UniversalSwap/SwapV3/index.module.scss
- Re-styled color for options percent in pool modal
=> update: styled color for options percent in pool modal

src/layouts/MenuV3.tsx, src/routes.tsx
Changes? 
- Redirect bridge to legacy
=> hot fix redirect bridge to legacy

src/pages/UniversalSwap/SwapV3/InputSwap.module.scss, src/pages/UniversalSwap/SwapV3/InputSwapV3.tsx, src/pages/UniversalSwap/SwapV3/index.module.scss, src/pages/UniversalSwap/SwapV3/index.tsx, src/styles/_themes.scss
- Update Swap UI according to design 
- Move % swap above pair selection
- Display pair price at below of selected pair
=> feat: add current price of selected pair

src/config/bridgeTokens.ts, src/pages/Balance/index.tsx, src/pages/UniversalSwap/SwapV3/InputSwapV3.tsx
- Refactor Filter list Universal Swap and Filter List EVM chain
=> refactor: filter list universal swap and filter list EVM chainID

src/config/chainInfos.ts
=> hotfix: update rpc noble

src/pages/Balance/index.tsx
- Add log sentry Oraichain-> Noble-1
=> add log sentry oraichain-> noble-1

src/pages/Pools/indexV3.module.scss, src/styles/_mixins.scss, src/styles/_variables.scss
=> fix: bug padding pool list on mac

src/helper/index.tsx, src/pages/Balance/index.tsx
- Push log error bridge usdc noble oraichain
=> push log error bridge usdc noble oraichain

src/layouts/MenuV3.tsx
=> update: change link  future

src/pages/Pools/hookV3.ts, src/pages/UniversalSwap/index.tsx
fix hide chart when data chart not found
=> fix: hide chart

.github/workflows/mainnet.yml, .github/workflows/pull-request-noti.yml
Purpose
+ Add a workflow for notifying when has a pull request 
+ Update workflow main: remove message on firebase, and delivery when create release instead of push to main
=> add and update workflows

package.json, src/components/Modals/SelectTokenModal/SelectTokenModal.tsx, src/pages/UniversalSwap/Component/TabsTxs.tsx, src/pages/UniversalSwap/Modals/SelectTokenModalV2.tsx, src/pages/UniversalSwap/helpers.ts, src/tests/helper.spec.ts, yarn.lock
- Update switch chart when pair not in pool 
- Find icon network and token
=> Update: switch chart when pair not in pool  universal swap

package.json, src/pages/UniversalSwap/helpers.ts, yarn.lock
- Check pair swap same ( example:  ORAI/ORAI => chart display: ORAI/USDT or AIRI/AIRI => chart display: ORAI/AIRI )
=> update: check pair swap equal

src/pages/Pools/helpers.ts, src/pages/UniversalSwap/SwapV3/index.tsx
- Fix number with commas expect output universal swap
=> fix: numberWithCommas expect output

src/helper/index.tsx, src/hooks/useLoadTokens.ts, src/libs/utils.ts
- Update get info when keplr ledger not support kawaii
=> Fix: get address ledger when keplr not support kawaii

src/pages/UniversalSwap/SwapV3/index.module.scss, src/pages/UniversalSwap/SwapV3/index.tsx, src/styles/_themes.scss
- Add warning slippage 0%
- Fix display minimum received
=> add: warning when slippage 0%

src/components/ConnectWallet/index.tsx, src/components/ConnectWallet/useResetBalance.ts, src/helper/index.tsx, src/layouts/App.tsx, src/pages/Balance/index.tsx, src/pages/UniversalSwap/SwapV3/index.tsx, src/tests/helper.spec.ts
- Reset cache balance when disconnect wallet
=> update reset cache balance when disconnect wallet

src/helper/index.tsx, src/pages/Balance/helpers.ts
- Hardcode Multiplier fee Osmosis
=> fix bridge osmosis -> oraichain

src/layouts/MenuV3.tsx
=> feat: add link futures legacy

src/config/chainInfos.ts
=> update rpc lcd osmosis chain

src/config/chainInfos.ts, src/libs/cosmjs.ts
- Update terdermint37 for getCosmwasmClient ( Error: Invalid string. Length must be a multiple of 4  => Node Osmosis using terdermint34 Incompatible with cosmos sdk 0.47 )
=> update terdermint 37 getCosmWasmClient

src/layouts/MenuV3.module.scss, src/layouts/MenuV3.tsx, src/pages/UniversalSwap/Modals/SelectTokenModalV2.module.scss, src/pages/UniversalSwap/Modals/SelectTokenModalV2.tsx, src/pages/UniversalSwap/SwapV3/index.module.scss, src/pages/UniversalSwap/SwapV3/index.tsx
- update ui modal select token
=> fix: update ui modal select token

src/pages/UniversalSwap/SwapV3/index.module.scss
=> fix: z-index swap section

src/helper/index.tsx, src/hooks/useLoadTokens.ts
- Fix ledger address when not get from chain coinType 60 ( Injective or Kawaii evm)
=> update address ledger

config-overrides.js
=> add source map

config-overrides.js
=> update release unique

src/pages/Pools/index.tsx
- Fix error crash when map icon pools
=> fix: icon pools

src/pages/Pools/helpers.ts, src/pages/Pools/index.tsx, src/tests/pool.spec.ts
- Reverse symbol pool ORAIX/USDC
=> reverse symbol pool oraix/usdc

package.json, src/config/chainInfos.ts, src/tests/universal-swap.spec.ts, yarn.lock
=> Add erc20 usdt

src/pages/CoHarvest/components/Bidding/index.tsx, src/pages/CoHarvest/components/BiddingChart/index.module.scss, src/pages/CoHarvest/components/BiddingChart/index.tsx, src/pages/CoHarvest/components/ChartColumn/index.module.scss, src/pages/CoHarvest/components/ChartColumn/index.tsx, src/pages/CoHarvest/components/InputBalance/index.tsx, src/pages/CoHarvest/helpers/index.ts, src/tests/coharvest.spec.ts
hotfix style and check volume chart
=> hotfix style and check volume chart

yarn.lock
=> fix allow token usdt erc20

package.json, src/pages/CoHarvest/components/CountDownTime/index.tsx, src/pages/CoHarvest/components/HarvestInfo/index.tsx, src/pages/CoHarvest/hooks/useCountdown.ts, src/pages/CoHarvest/index.tsx, yarn.lock
=> refactor: count down

src/pages/CoHarvest/components/AllBidding/index.tsx, src/pages/CoHarvest/components/Bidding/index.tsx, src/pages/CoHarvest/components/BiddingHistory/index.tsx, src/pages/CoHarvest/components/HarvestInfo/index.tsx, src/pages/CoHarvest/components/MyBidding/index.tsx, src/pages/CoHarvest/hooks/useGetBidRound.ts, src/pages/CoHarvest/index.tsx
- Fix price USD bidding history
=> fix price bidding history

src/pages/CoHarvest/hooks/useCountdown.ts
=> fix: update disable bid

src/pages/CoHarvest/hooks/useGetBidRound.ts
=> feat: get current bid

.env.example, src/layouts/BuyOraiModal.module.scss, src/layouts/BuyOraiModal.tsx, src/layouts/Menu.tsx, src/styles/_themes.scss
=> feat: add kado

src/pages/CoHarvest/components/Bidding/index.module.scss, src/pages/CoHarvest/components/Bidding/index.tsx, src/pages/CoHarvest/components/BiddingChart/index.tsx, src/pages/CoHarvest/components/CountDownTime/index.tsx, src/pages/CoHarvest/components/HarvestInfo/index.module.scss, src/pages/CoHarvest/components/HarvestInfo/index.tsx, src/pages/CoHarvest/components/InputBalance/index.module.scss, src/pages/CoHarvest/components/InputBalance/index.tsx
=> fix: label co harvest page

config-overrides.js, package.json, yarn.lock
=> update src map

src/layouts/App.tsx
feat: remove modal competition
=> feat: remove modal competition

src/pages/CoHarvest/components/CountDownTime/index.tsx
fix: display start time and end time coharvest
=> fix: display start time and end time coharvest

src/pages/Pools/components/Filter/Filter.tsx
=> fix: my pool list

package.json, src/layouts/NoticeBanner.tsx, src/libs/keplr.ts
=> fix: rm banner timpi

src/components/Modal.module.scss, src/pages/Pools/components/AddLiquidityModal/AddLiquidityModal.module.scss, src/pages/Pools/components/InputWithOptionPercent/InputWithOptionPercent.module.scss, src/pages/Pools/components/StakeLPModal/StakeLPModal.module.scss, src/pages/Pools/components/UnstakeLPModal/UnstakeLPModal.module.scss, src/pages/Pools/components/WithdrawLiquidityModal/WithdrawLiquidityModal.module.scss
=> feat: update ui modal pool

src/pages/UniversalSwap/SwapV3/hooks/useFillToken.ts, src/pages/UniversalSwap/SwapV3/index.tsx
=> feat: auto fill token swap

package.json, scripts/vendor.js, src/hooks/useTokenFee.ts, yarn.lock
- Ignore vendor package oraidex-common-ui for debug Sentry
- Pumb version oraidex-common-ui
=> Fix/ignore common UI

src/pages/Pools/components/AddLiquidityModal/AddLiquidityModal.tsx, src/pages/Pools/components/OverviewPool/OverviewPool.tsx
=> fix:sentry

package.json, yarn.lock
=> chore: pump version common ui

src/layouts/Menu.tsx
- Add beta link for new wallet management
=> chore: add beta link test

src/pages/UniversalSwap/SwapV3/hooks/useFillToken.ts
fix: check milky or kwt when swap
=> fix: check milky or kwt when swap

src/components/Button/Button.module.scss, src/components/Button/Button.tsx, src/layouts/Content.tsx, src/layouts/NoticeBanner.module.scss, src/layouts/NoticeBanner.tsx, src/layouts/index.scss, src/pages/CoHarvest/index.module.scss, src/pages/Maintenance/index.tsx, src/pages/Pools/PoolDetail.tsx, src/pages/Pools/components/ChartDetailContent/index.module.scss, src/pages/Pools/components/Header/Header.module.scss, src/pages/Pools/components/Header/Header.tsx, src/pages/Pools/components/MyPoolInfo/MyPoolInfo.tsx, src/pages/Pools/index.tsx, src/styles/_utils.scss, src/styles/_variables.scss
=> fix: bg, banner

src/pages/Pools/components/TransactionHistory/index.tsx, src/pages/Pools/helpers.ts
=> fix: txs table amount

src/pages/BitcoinDashboard/components/Checkpoint/Checkpoint.tsx, src/pages/BitcoinDashboard/components/PendingWithdraws/PendingWithdraws.tsx
=> fix pending withdraws and info notification on checkpoint

src/pages/Staking/hooks/useGetMyStakeRewardInfo.ts
=> fix: staking reward

package.json, yarn.lock
- Safe update all dependencies
=> Safe update all dependencies

src/components/WalletManagement/MyWallet/MyWallet.tsx, src/pages/UniversalSwap/SwapV3/hooks/useFillToken.ts
- Guard code validate object to prevent crash
=> hotfix: validate object to prevent crash

src/pages/CoHarvest/helpers/index.ts
=> fix: tx time table

src/pages/BitcoinDashboard/components/Checkpoint/Checkpoint.module.scss, src/pages/BitcoinDashboard/components/Checkpoint/Checkpoint.tsx, src/pages/BitcoinDashboard/components/Checkpoint/Transactions/TransactionInput.tsx, src/pages/BitcoinDashboard/components/Checkpoint/Transactions/TransactionMobiles/TransactionMobile.module.scss, src/pages/BitcoinDashboard/components/Checkpoint/Transactions/TransactionMobiles/TransactionMobile.tsx, src/pages/BitcoinDashboard/components/Checkpoint/Transactions/TransactionMobiles/index.ts, src/pages/BitcoinDashboard/components/Checkpoint/Transactions/TransactionOutput.tsx, src/pages/BitcoinDashboard/components/PendingDeposits/PendingDeposits.tsx, src/pages/BitcoinDashboard/components/PendingWithdraws/PendingWithdraws.tsx, src/pages/BitcoinDashboard/components/RenderIf/RenderIf.tsx, src/pages/BitcoinDashboard/components/RenderIf/index.ts, src/pages/BitcoinDashboard/utils/validate.ts
* Current table UI is not suitable for mobile
* See in file changes.
=> update UI bitcoin-dashboard for mobile

src/layouts/App.tsx, src/layouts/NoticeBanner.tsx
=> fix: banner no data

src/pages/BitcoinDashboard/@types/Checkpoint.types.ts, src/pages/BitcoinDashboard/components/PendingWithdraws/PendingWithdraws.tsx
=> fix ui pending withdraws

src/pages/Pools/hooks/hooks.ts
=> chore: hide pool orai/btc

src/pages/Pools/hooks/hooks.ts
=> update: reopen oraibtc pool

src/pages/Pools/PoolDetail.tsx, src/pages/Pools/components/TransactionHistory/index.tsx
- Guard code & refactor some logic
=> fix: guard code & refactor some logic

yarn.lock
What is purpose of the changes? 
- Pumb oraidex-common
=> chore: pumb oraidex-common

src/pages/Balance/helpers.ts
-  Add fallback data for api get deposit fees bitcoin to prevent crash
=> fix: add fallback data for api get deposit fees bitcoin

src/hooks/useTokenFee.ts, src/pages/CoHarvest/hooks/useGetBidRound.ts, src/pages/Pools/components/LiquidityChart/index.tsx, src/pages/Pools/components/VolumeChart/index.tsx, src/rest/api.ts
fix: sentry chart and get bid round
=> fix: sentry chart and get bid round

src/hooks/useLoadTokens.ts
- Not throw error when load evm failed
=> fix: load evm balance

src/layouts/NoticeBanner.tsx
=> fix: sentry banner

src/pages/Balance/Balance.module.scss, src/pages/Balance/DepositBtcModal/index.tsx, src/pages/Balance/TokenItem/TokenItemBtc.tsx, src/pages/Balance/TokenItem/index.tsx, src/pages/Balance/index.tsx
- Only support Owallet Bitcoin
- Show Address Oraichain in modal BTC Deposit
=> [REVIEW] - Fix BTC Deposit

src/config/bridgeTokens.ts, src/routes.tsx, src/store/constants.ts
=> fix: cache Pool list

src/pages/CoHarvest/hooks/useGetBidRound.ts, src/pages/Pools/hooks/hooks.ts, src/pages/Staking/components/StakeTab/index.tsx
=> fix: sentry

src/hooks/useLoadTokens.ts, src/pages/CoHarvest/components/Bidding/index.tsx, src/pages/Staking/components/StakeInfo/index.tsx, src/pages/Staking/components/StakeTab/index.tsx, src/pages/Staking/components/UnStakeTab/index.tsx
=> fix: load oraichain token

src/layouts/Content.module.scss, src/layouts/NoticeBanner.module.scss, src/layouts/Sidebar.module.scss, src/layouts/index.scss, src/pages/CoHarvest/components/Banner/index.module.scss, src/pages/CoHarvest/components/BiddingChart/index.module.scss, src/pages/CoHarvest/components/BiddingChart/index.tsx, src/pages/CoHarvest/components/BiddingHistory/index.module.scss, src/pages/CoHarvest/components/ChartColumn/index.module.scss, src/pages/CoHarvest/components/HarvestInfo/index.module.scss, src/pages/CoHarvest/components/InputBalance/index.module.scss, src/pages/CoHarvest/index.module.scss, src/styles/_themes.scss, src/styles/_variables.scss
=> fix: layout

src/components/WalletManagement/ModalChooseWallet/WalletByNetwork/WalletByNetwork.tsx, src/helper/index.tsx, src/hooks/useMetamask.ts, src/layouts/App.tsx
- Add condition when connect metamask evm to prevent popup of eip191
=> chore: add condition when connect metamask evm

src/pages/UniversalSwap/Swap/components/AddressBook/index.tsx
=> fix: swap book

src/layouts/App.tsx
=> fix: hide dao popup

src/pages/Pools/components/Header/Header.tsx
fix: maximum call update pool page
=> fix: maximum call update pool page

src/components/Table/Table.tsx
- Revert readonly error fix of the sortDataSource function in Table.tsx
=> revert fix

src/components/Table/Table.tsx
=> fix: crash table

src/index.tsx, src/pages/UniversalSwap/Swap/index.tsx
=> fix: sentry , ignore error

src/hooks/useWindowSize.ts, src/pages/UniversalSwap/Component/HeaderTab.module.scss, src/pages/UniversalSwap/Component/HeaderTab.tsx, src/pages/UniversalSwap/index.module.scss, src/pages/UniversalSwap/index.tsx
=> feat: add chart mobile

src/components/ModalCustom/index.module.scss, src/components/ModalCustom/index.tsx, src/pages/UniversalSwap/Component/ChartUsdPrice.module.scss, src/pages/UniversalSwap/Component/HeaderTab.module.scss, src/pages/UniversalSwap/Component/HeaderTab.tsx, src/pages/UniversalSwap/index.module.scss, src/pages/UniversalSwap/index.tsx
=> feat: update chart mobile

src/pages/UniversalSwap/Component/AssetsTab.module.scss, src/pages/UniversalSwap/Component/AssetsTab.tsx, src/pages/UniversalSwap/Swap/components/SelectChain/SelectChain.module.scss, src/pages/UniversalSwap/Swap/components/SelectChain/SelectChain.tsx, src/pages/UniversalSwap/Swap/components/SelectToken/SelectToken.module.scss, src/pages/UniversalSwap/Swap/hooks/useSwapFee.ts, src/pages/UniversalSwap/index.module.scss
=> fix: swap select

src/pages/UniversalSwap/index.tsx
=> fix: price usd chart

src/layouts/Sidebar.tsx, src/pages/UniversalSwap/index.tsx
=> feat: end birthday event

src/helper/index.tsx, src/pages/UniversalSwap/Swap/index.tsx, src/tests/helper.spec.ts
=> fix: number exponent

src/pages/CoHarvest/components/HarvestInfo/index.tsx, src/pages/Staking/components/Summary/index.tsx
=> fix: text tooltip

src/assets/icons/arrow_right_ic.svg, src/components/Tooltip.module.scss, src/components/Tooltip.tsx, src/pages/Staking/components/CompoundModal/index.module.scss, src/pages/Staking/components/CompoundModal/index.tsx, src/pages/Staking/components/StakeInfo/index.module.scss, src/pages/Staking/components/StakeInfo/index.tsx
=> feat: staking compound

src/pages/Staking/components/StakeInfo/index.tsx
=> hotfix compound

src/pages/Pool-V3/components/PoolList/index.module.scss, src/pages/Pool-V3/components/PoolList/index.tsx
=> feat: add tooltip apr

src/pages/Pools/components/Earning/Earning.tsx, src/pages/Pools/hooks/hooks.ts
=> fix: get all pending reward

src/pages/Balance/Balance.module.scss, src/pages/Balance/index.tsx, src/pages/UniversalSwap/Swap/components/SelectChain/SelectChain.tsx
=> fix: add maintain bridge

package.json, yarn.lock
=> fix: list token

src/styles/_themes.scss
fix: add missing color variable
=> fix: add missing color variable

src/pages/Pools/hooks/useLiquidityEventChart.ts
- Update timeframe chart liquidity pool to latest 90 days.
=> update: update timeframe chart liquidity pool to 90 days.

src/components/Pagination/usePagination.ts, src/pages/UniversalSwap/Swap/hooks/useCalculateDataSwap.ts, src/pages/UniversalSwap/Swap/index.module.scss, src/pages/UniversalSwap/Swap/index.tsx
- Fix search token & no routes found swap
=> Fix search token & no routes found swap

package.json, src/helper/index.tsx, src/hooks/useLoadTokens.ts, src/pages/UniversalSwap/Swap/hooks/useSimulate.ts, yarn.lock
fix: frendly message error 429
=> fix: frendly message error 429

src/pages/Pools/components/OverviewPool/OverviewPool.tsx
=> feat: add ORAI-BTC allocation display in OverviewPool component

vite.config.ts
=> chunk file build source map sentry
